export const SUBMISSION_STATUS_SETTING = 'SETTING'; 
export const SUBMISSION_STATUS_SUBMITTED = 'SUBMITTED'; 
export const SUBMISSION_STATUS_SUCCESS = 'SUCCESS'; 
export const SUBMISSION_STATUS_FAILED = 'FAILED'; 
